stages:          # List of stages for jobs, and their order of execution
  - deploy
build-job:       # This job runs in the build stage, which runs first.
  stage: deploy
  image: maven:3.8-openjdk-11
  script:
    - cd lib
    - bash install_corpus_services_jar.sh
    - cd ..
    - mvn compile assembly:single
  artifacts:
     name: "release"
     paths:
         - target/corpus-web-service-1.0-SNAPSHOT.jar
