---
# This is a basic workflow to help you get started with Actions

name: Publish CI build as new release

# Controls when the workflow will run
on:
  # Only run if the CI build succeeded
  workflow_run:
    workflows: [Java CI with Maven]
    branches: 
      - main
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially
# or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part
    # of the job
    steps:
      - name: Display structure of downloaded files
        run: ls -R
      - name: Install node packages
        run: npm install moment
      - uses: actions/github-script@v7
        with:
          debug: false
          script: |
            const moment = require('moment')
            const fs = require('fs');
            tag_name = moment().format('YYYYMMDD-HHmmss');
            releaseInfo = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name});
            console.log(releaseInfo);
            releaseId = releaseInfo.data.id;
            releaseUrl = releaseInfo.data.upload_url;
            artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            artifacts.data.artifacts.sort(function(a,b){return Date.parse(b["created_at"]) - Date.parse(a["created_at"])})
            artifactId = artifacts.data.artifacts[0].id;
            result = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: artifactId,
              archive_format: "zip",
              });
            zipData = result.data;
            result = await github.request({
              method: "POST",
              url: releaseUrl,
              headers: {
                "content-type": "application/zip",
                },
              data: zipData,
              name: "corpus-web-services.zip",
              label: "Build",
              });
            console.log(result);
